import { Match, Player, Strategy, MapData } from './types';

export const MAPS = ['Reactor', 'Nexus', 'Outpost', 'Factory', 'Skyline', 'Bunker', 'Haven', 'Citadel'];

export const DIVISIONS = ['Division 1', 'Division 2', 'Division 3', 'Open Qualifier', 'Playoffs', 'Grand Final'];

export const initialPlayers: Player[] = [
  {
    id: 'p1',
    pseudo: 'Neo',
    role: 'Entry Fragger',
    poste: 'Attaquant',
    avatar: '⚡',
    available: true,
    favoriteMaps: ['Reactor', 'Nexus', 'Skyline'],
    stats: { kills: 342, deaths: 198, assists: 87, matchesPlayed: 28, wins: 19, mvpCount: 8 },
    eloRating: 1850,
  },
  {
    id: 'p2',
    pseudo: 'Vex',
    role: 'Support',
    poste: 'Support',
    avatar: '🛡️',
    available: true,
    favoriteMaps: ['Reactor', 'Factory', 'Haven'],
    stats: { kills: 210, deaths: 165, assists: 195, matchesPlayed: 28, wins: 19, mvpCount: 3 },
    eloRating: 1720,
  },
  {
    id: 'p3',
    pseudo: 'Kira',
    role: 'Flex',
    poste: 'Flex',
    avatar: '🔥',
    available: true,
    favoriteMaps: ['Reactor', 'Nexus', 'Outpost'],
    stats: { kills: 298, deaths: 180, assists: 142, matchesPlayed: 28, wins: 19, mvpCount: 6 },
    eloRating: 1800,
  },
  {
    id: 'p4',
    pseudo: 'Ghost',
    role: 'Lurker',
    poste: 'Flanker',
    avatar: '👻',
    available: true,
    favoriteMaps: ['Nexus', 'Bunker', 'Citadel'],
    stats: { kills: 265, deaths: 172, assists: 98, matchesPlayed: 25, wins: 16, mvpCount: 5 },
    eloRating: 1780,
  },
  {
    id: 'p5',
    pseudo: 'Lux',
    role: 'AWPer',
    poste: 'Sniper',
    avatar: '🎯',
    available: false,
    favoriteMaps: ['Nexus', 'Skyline', 'Haven'],
    stats: { kills: 310, deaths: 155, assists: 62, matchesPlayed: 26, wins: 18, mvpCount: 9 },
    eloRating: 1900,
  },
  {
    id: 'p6',
    pseudo: 'Blitz',
    role: 'IGL',
    poste: 'Leader',
    avatar: '🧠',
    available: true,
    favoriteMaps: ['Reactor', 'Factory', 'Bunker'],
    stats: { kills: 245, deaths: 190, assists: 168, matchesPlayed: 28, wins: 19, mvpCount: 4 },
    eloRating: 1760,
  },
];

export const initialMatches: Match[] = [
  {
    id: 'm1',
    date: '2026-01-20',
    time: '20:00',
    opponent: 'Phoenix Blaze',
    opponentLogo: '🐦',
    division: 'Division 1',
    format: 'BO3',
    status: 'completed',
    lineup: ['p1', 'p2', 'p3', 'p4', 'p6'],
    scores: [
      { map: 'Reactor', teamScore: 13, opponentScore: 9 },
      { map: 'Nexus', teamScore: 11, opponentScore: 13 },
      { map: 'Skyline', teamScore: 13, opponentScore: 7 },
    ],
    mvp: 'p1',
    pickBan: {
      teamPicks: ['Reactor', 'Skyline'],
      teamBans: ['Outpost', 'Haven'],
      opponentPicks: ['Nexus'],
      opponentBans: ['Factory', 'Bunker'],
    },
  },
  {
    id: 'm2',
    date: '2026-01-22',
    time: '21:00',
    opponent: 'Shadow Wolves',
    opponentLogo: '🐺',
    division: 'Division 1',
    format: 'BO3',
    status: 'completed',
    lineup: ['p1', 'p2', 'p3', 'p5', 'p6'],
    scores: [
      { map: 'Factory', teamScore: 13, opponentScore: 11 },
      { map: 'Bunker', teamScore: 13, opponentScore: 8 },
    ],
    mvp: 'p5',
    pickBan: {
      teamPicks: ['Factory'],
      teamBans: ['Citadel', 'Haven'],
      opponentPicks: ['Bunker'],
      opponentBans: ['Reactor', 'Nexus'],
    },
  },
  {
    id: 'm3',
    date: '2026-01-25',
    time: '19:30',
    opponent: 'Neon Strikers',
    opponentLogo: '⚡',
    division: 'Playoffs',
    format: 'BO3',
    status: 'completed',
    lineup: ['p1', 'p3', 'p4', 'p5', 'p6'],
    scores: [
      { map: 'Nexus', teamScore: 8, opponentScore: 13 },
      { map: 'Reactor', teamScore: 13, opponentScore: 10 },
      { map: 'Haven', teamScore: 9, opponentScore: 13 },
    ],
    mvp: 'p3',
    pickBan: {
      teamPicks: ['Reactor', 'Haven'],
      teamBans: ['Skyline', 'Citadel'],
      opponentPicks: ['Nexus'],
      opponentBans: ['Factory', 'Outpost'],
    },
  },
  {
    id: 'm4',
    date: '2026-01-28',
    time: '20:00',
    opponent: 'Iron Vanguard',
    opponentLogo: '🛡️',
    division: 'Division 1',
    format: 'BO1',
    status: 'upcoming',
    lineup: ['p1', 'p2', 'p3', 'p4', 'p6'],
    scores: [],
    pickBan: {
      teamPicks: ['Reactor'],
      teamBans: ['Outpost', 'Citadel'],
      opponentPicks: [],
      opponentBans: ['Nexus', 'Factory'],
    },
  },
  {
    id: 'm5',
    date: '2026-02-01',
    time: '21:00',
    opponent: 'Cyber Dragons',
    opponentLogo: '🐉',
    division: 'Division 1',
    format: 'BO3',
    status: 'upcoming',
    lineup: [],
    scores: [],
  },
  {
    id: 'm6',
    date: '2026-02-05',
    time: '19:00',
    opponent: 'Storm Riders',
    opponentLogo: '🌩️',
    division: 'Playoffs',
    format: 'BO5',
    status: 'upcoming',
    lineup: [],
    scores: [],
  },
];

export const initialStrategies: Strategy[] = [
  {
    id: 's1',
    name: 'Rush B Reactor',
    map: 'Reactor',
    type: 'offensive',
    description: 'Rush coordonné site B avec flash + smoke. Entry par Neo, support Vex. Kira couvre mid.',
    notes: 'Fonctionne très bien contre les défenses passives. Timing critique: 1:15 round timer.',
    createdBy: 'Coach Dyno',
    createdAt: '2026-01-10',
  },
  {
    id: 's2',
    name: 'Default Nexus',
    map: 'Nexus',
    type: 'defensive',
    description: 'Setup défensif classique 2-1-2. Retake B possible avec rotation rapide depuis mid.',
    notes: 'Attention aux push mid rapides. Ghost doit hold angle B long.',
    createdBy: 'Coach Dyno',
    createdAt: '2026-01-12',
  },
  {
    id: 's3',
    name: 'Fake A into B',
    map: 'Factory',
    type: 'offensive',
    description: 'Fausse exécution site A (flash + smoke) puis rotation silencieuse site B.',
    notes: 'Nécessite discipline, pas de contact A. Timing rotation: après smoke A posé.',
    createdBy: 'Coach Dyno',
    createdAt: '2026-01-15',
  },
];

export const mapStatsData: MapData[] = [
  { name: 'Reactor', winRate: 78, totalGames: 18, wins: 14, losses: 4 },
  { name: 'Nexus', winRate: 55, totalGames: 11, wins: 6, losses: 5 },
  { name: 'Factory', winRate: 72, totalGames: 9, wins: 6, losses: 3 },
  { name: 'Skyline', winRate: 80, totalGames: 5, wins: 4, losses: 1 },
  { name: 'Bunker', winRate: 67, totalGames: 6, wins: 4, losses: 2 },
  { name: 'Haven', winRate: 40, totalGames: 5, wins: 2, losses: 3 },
  { name: 'Outpost', winRate: 50, totalGames: 4, wins: 2, losses: 2 },
  { name: 'Citadel', winRate: 60, totalGames: 5, wins: 3, losses: 2 },
];

export const seasonProgressData = [
  { week: 'S1', wins: 2, losses: 1 },
  { week: 'S2', wins: 3, losses: 0 },
  { week: 'S3', wins: 2, losses: 1 },
  { week: 'S4', wins: 1, losses: 2 },
  { week: 'S5', wins: 3, losses: 1 },
  { week: 'S6', wins: 2, losses: 0 },
  { week: 'S7', wins: 2, losses: 1 },
  { week: 'S8', wins: 3, losses: 0 },
];